baseURL = 'https://guides.muthu.co'
languageCode = 'en-us'
title = 'Beginner’s Guide to Programming Languages'
theme = 'typo'

# Google analytics code
googleAnalytics = "G-78L71VCGB2"

[taxonomies]
tag = 'tags'

[params]
# Meta description
description = "Discover beginner-friendly guides to 100+ programming languages. From JavaScript to Rust, learn coding fundamentals with clear explanations and practical examples."
showFooter = true
footerContent = "Made with ♥ in India"
faviconPath = "/"

# Appearance settings
theme = 'light'
colorPalette = 'eink'
hideHeader = true

# Intro on main page, content is markdown
# homeIntroTitle = 'Hello!'
# homeIntroContent = ""

# Collection to display on home
homeCollectionTitle = 'Guides'
homeCollection = 'posts'

# Lists parameters
paginationSize = 100
listSummaries = false
listDateFormat = '2 Jan 2006'

# Breadcrumbs
breadcrumbs = true

# Social icons
# [[params.social]]
# name = "linkedin"
# url = "https://www.linkedin.com/in/krimuthu/"

# [[params.social]]
# name = "github"
# url = "https://github.com/muthuspark"

# Main menu pages
[[params.menu]]
name = "home"
url = "/"

# [[params.menu]]
# name = "posts"
# url = "/posts"

[[params.menu]]
name = "about"
url = "/about"

[markup]
[markup.highlight]
style = 'friendly'